[font]
size = 12.0

[font.normal]
family = "Terminus"  # Set your desired font family here
style = "Regular"

[font.offset]
x = -1
y = -1

[window]
opacity = 0.65

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true
